version: '2.1'
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Install Snyk
          command: npm install --prefix=$HOME/.local -g snyk
      - run:
          name: Snyk Open Source
          command: snyk test --severity-threshold=high || true
      - run:
          name: Install Snyk to HTML
          command: npm install --prefix=$HOME/.local -g snyk-to-html
      - run:
          name: Snyk Code
          command: snyk code test --json | snyk-to-html -o code-results.html
      - store_artifacts:
          path: code-results.html
      - run:
          name: Snyk Container
          command: snyk container test --severity-threshold=high csantana/demo-spring:$CIRCLE_SHA1 || true
      - run:
          name: Snyk IaC
          command: snyk iac test --severity-threshold=high || true
      - snyk/scan:
          monitor-on-build: false
          fail-on-issues: false

  
     

workflows: null

  





