version: '2.1'
orbs:
  snyk: snyk/snyk@1.2.3
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - run: npm ci
      - snyk/scan
 
      - run:
          name: Install Snyk
          command: npm install --prefix=$HOME/.local -g snyk
      - run:
          name: Snyk Open Source
          command: snyk test --severity-threshold=high || true
      - run:
          name: Install Snyk to HTML
          command: npm install --prefix=$HOME/.local -g snyk-to-html
      - run:
          name: Snyk Code
          command: snyk code test --json | snyk-to-html -o code-results.html
      - store_artifacts:
          path: code-results.html
      
      - script: |
      curl -Lo ./snyk.exe "https://static.snyk.io/cli/latest/snyk-win.exe"
      chmod +x snyk.exe
      ls -la
      snyk.exe -v
    displayName: 'Snyk install'
  - script: |
      curl -Lo ./snyk-to-html.exe "https://static.snyk.io/snyk-to-html/latest/snyk-to-html-win.exe"
      chmod +x snyk-to-html.exe
      ls -la
    displayName: 'Snyk to html install'

    
          
 
     

workflows: null

  





