version: '2.1'
orbs:
  snyk: snyk/snyk@1.2.3
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - run: npm ci
      - snyk/scan
 
      - run:
          name: Install Snyk
          command: npm install --prefix=$HOME/.local -g snyk
      - run:
          name: Snyk Open Source
          command: snyk test --severity-threshold=high || true
      - run:
          name: Install Snyk to HTML
          command: npm install --prefix=$HOME/.local -g snyk-to-html
          
 
     

workflows: null

  





