name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.ACTIONS_SNYK_TOKEN }}
          
          # Install and Authenticate to Snyk
      
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          sudo npm install -g snyk-to-html
          snyk auth ${{ secrets.ACTIONS_SNYK_TOKEN }}
        # Run Snyk Code
      - name: Run Snyk 
        run: |
          snyk test  
 
